# Generated by Django 4.1 on 2024-03-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
