# Generated by Django 4.1 on 2024-04-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Calculator', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='morning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='night',
            field=models.BooleanField(default=False),
        ),
    ]
