# Generated by Django 4.1 on 2024-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Calculator', '0008_alter_ingredient_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='input_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
