# Generated by Django 4.1 on 2024-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Calculator', '0011_alter_food_calcium_alter_food_carbohydrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=0),
        ),
    ]
