# Generated by Django 4.1 on 2024-05-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Calculator', '0013_ingredient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='input_date',
            field=models.DateField(),
        ),
    ]
